### ISSUE TITLE
[Chapter 3]: Error while installing pk interpreter

### ISSUE THREAD

**Issue by AugustoRGomez** [goossens-springer/goossens-book-ip-projects#1]
Hi,

I was trying to install pk interpreter in my computer, everything goes fine until I have to execute make file, I receive the following errors: 

![image](https://user-images.githubusercontent.com/82985923/234389000-ed41b283-9082-4cf5-9906-2ba2fe66ebb4.png)

Can please somebody help me with this one? 
Regards

Augusto

**Comment by goossens-springer** [comment]
Hello Augusto, 

I'll have a look at that and keep you informed soonly. 

Best regards, bg. 


De: "AugustoRGomez" ***@***.***> 
À: "goossens-springer/goossens-book-ip-projects" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 21:59:06 
Objet: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 





Hi, 

I was trying to install pk interpreter in my computer, everything goes find until I have to execute make file, i receive the following errors: 

[ https://user-images.githubusercontent.com/82985923/234389000-ed41b283-9082-4cf5-9906-2ba2fe66ebb4.png ] 

Can please somebody help me with this one? 
Regards 

Augusto

**Comment by goossens-springer** [comment]
Hello Augusto, 

I tried to re-install pk on my laptop and it works fine. 

Did you install the toolchain (the riscv cross compiler "riscv32-unknown-elf-gcc") just before the spike and pk installations ? If not, I recommend that you redo the full installation (in the book, from page 87 to 91). 

Please, keep me informed on your progress. 

Sincerely, bg. 


De: "Bernard Goossens" ***@***.***> 
À: "goossens-springer" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 22:52:20 
Objet: Re: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 

Hello Augusto, 

I'll have a look at that and keep you informed soonly. 

Best regards, bg. 


De: "AugustoRGomez" ***@***.***> 
À: "goossens-springer/goossens-book-ip-projects" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 21:59:06 
Objet: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 





Hi, 

I was trying to install pk interpreter in my computer, everything goes find until I have to execute make file, i receive the following errors: 

[ https://user-images.githubusercontent.com/82985923/234389000-ed41b283-9082-4cf5-9906-2ba2fe66ebb4.png ] 

Can please somebody help me with this one? 
Regards 

Augusto

**Comment by goossens-springer** [comment]
Hello Roberto, 

I have been trying to re-install the full toolchain and it ends the same way as you. 
It comes from a change in the RISCV specification. 
I have browsed a little to find a way around but with no solution for now. 

bg. 


De: "Bernard Goossens" ***@***.***> 
À: "goossens-springer" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 23:15:34 
Objet: Re: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 

Hello Augusto, 

I tried to re-install pk on my laptop and it works fine. 

Did you install the toolchain (the riscv cross compiler "riscv32-unknown-elf-gcc") just before the spike and pk installations ? If not, I recommend that you redo the full installation (in the book, from page 87 to 91). 

Please, keep me informed on your progress. 

Sincerely, bg. 


De: "Bernard Goossens" ***@***.***> 
À: "goossens-springer" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 22:52:20 
Objet: Re: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 

Hello Augusto, 

I'll have a look at that and keep you informed soonly. 

Best regards, bg. 


De: "AugustoRGomez" ***@***.***> 
À: "goossens-springer/goossens-book-ip-projects" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 21:59:06 
Objet: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 





Hi, 

I was trying to install pk interpreter in my computer, everything goes find until I have to execute make file, i receive the following errors: 

[ https://user-images.githubusercontent.com/82985923/234389000-ed41b283-9082-4cf5-9906-2ba2fe66ebb4.png ] 

Can please somebody help me with this one? 
Regards 

Augusto

**Comment by goossens-springer** [comment]
Hello Roberto, 

There is a work around: you need to install the same version of the toolchain and the tools as mine, using the hash of the git version cloned. 
I'll check for the hash value to be used later in the day and keep you informed this evening. 

bg. 


De: "Bernard Goossens" ***@***.***> 
À: "goossens-springer" ***@***.***> 
Envoyé: Mercredi 26 Avril 2023 10:08:12 
Objet: Re: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 

Hello Roberto, 

I have been trying to re-install the full toolchain and it ends the same way as you. 
It comes from a change in the RISCV specification. 
I have browsed a little to find a way around but with no solution for now. 

bg. 


De: "Bernard Goossens" ***@***.***> 
À: "goossens-springer" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 23:15:34 
Objet: Re: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 

Hello Augusto, 

I tried to re-install pk on my laptop and it works fine. 

Did you install the toolchain (the riscv cross compiler "riscv32-unknown-elf-gcc") just before the spike and pk installations ? If not, I recommend that you redo the full installation (in the book, from page 87 to 91). 

Please, keep me informed on your progress. 

Sincerely, bg. 


De: "Bernard Goossens" ***@***.***> 
À: "goossens-springer" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 22:52:20 
Objet: Re: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 

Hello Augusto, 

I'll have a look at that and keep you informed soonly. 

Best regards, bg. 


De: "AugustoRGomez" ***@***.***> 
À: "goossens-springer/goossens-book-ip-projects" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Mardi 25 Avril 2023 21:59:06 
Objet: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 





Hi, 

I was trying to install pk interpreter in my computer, everything goes find until I have to execute make file, i receive the following errors: 

[ https://user-images.githubusercontent.com/82985923/234389000-ed41b283-9082-4cf5-9906-2ba2fe66ebb4.png ] 

Can please somebody help me with this one? 
Regards 

Augusto

**Comment by AugustoRGomez** [comment]
Hi Bernard, thanks for your response,
Yes, I installed riscv cross compiler before installing spike and pk,
As you said, there was a change in RV32 spec and maybe that's causing the problem,
Let me know when you find the hash value you used for git clone

Augusto

**Comment by AugustoRGomez** [comment]
Hi Bernard, 
Thanks, i will re download the tools later, but in the meanwhile I was capable of build pk with:
`../configure --prefix=$RISCV --host=riscv32-unknown-elf --with-arch=rv32gc` and then I could run makefile successfully.

Augusto. (Not Roberto 😆)

**Comment by goossens-springer** [comment]
Ok. With this version of the compiler, you'll have to compile with the march and mabi options to avoid generating a mix of 32-bit and 16-bit instructions: 
riscv32-unknown-elf-gcc -march=rv32i -mabi=ilp32 

(all my implementations concern pure rv32i isa, no rv32c extension). 


De: "AugustoRGomez" ***@***.***> 
À: "goossens-springer/goossens-book-ip-projects" ***@***.***> 
Cc: "Bernard Goossens" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Jeudi 27 Avril 2023 21:06:52 
Objet: Re: [goossens-springer/goossens-book-ip-projects] [Chapter 3]: Error while installing pk interpreter (Issue #1) 





Hi Bernard, 
Thanks, i will re download the tools later, but in the meanwhile I was capable of build pk with: 
../configure --prefix=$RISCV --host=riscv32-unknown-elf --with-arch=rv32gc and then I could run makefile successfully. 

Augusto. (Not Roberto \uD83D\uDE06)

**Comment by AugustoRGomez** [comment]
Hi Bernand,
Yes, I successfully installed pk with the method you proposed, thank you.
Closing the issue.

Regards,
Augusto.
